export const SUBMIT_CREATE_EVENT_ACTION = "SUBMIT_CREATE_EVENT_ACTION";
export const GET_ALL_EVENTS_ACTION = "GET_ALL_EVENTS_ACTION";
export const GET_ALL_EVENTS_RESPONSE = "GET_ALL_EVENTS_RESPONSE";
export const GET_EVENT_DETAILS_ACTION = "GET_EVENT_DETAILS_ACTION";
export const GET_EVENT_DETAILS_RESPONSE = "GET_EVENT_DETAILS_RESPONSE";
export const BOOK_EVENT_ACTION = "BOOK_EVENT_ACTION";
