export const SUBMIT_LOGIN_ACTION = "SUBMIT_LOGIN_ACTION";
export const GET_LOGIN_SUBMITTED_DATA = "GET_LOGIN_SUBMITTED_DATA";
export const SUBMIT_REGISTRATION_ACTION = "SUBMIT_REGISTRATION_ACTION";
export const VERIFY_EMAIL_ACTION = "VERIFY_EMAIL_ACTION";
export const SUBMIT_COMPLETE_PROILE_ACTION = "SUBMIT_COMPLETE_PROILE_ACTION";
export const RESEND_VERIFICATION_EMAIL_ACTION =
  "RESEND_VERIFICATION_EMAIL_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const GET_LOOKUPS_ACTION = "GET_LOOKUPS_ACTION";
export const LIST_LOOKUPS = "LIST_LOOKUPS";
